[tool.poetry]
name = "compile"
version = "0.1.0"
authors = ["Aderoju"]

[tool.poetry.dependencies]
python
mysql-connector-python
pandas

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
